package script.db

databaseChangeLog(logicalFilePath: 'script/db/scux_rcwl_pr_line_his.groovy') {
    changeSet(author: "jie.wang05@hand-china.com", id: "2021-11-03-scux_rcwl_pr_line_his") {
        def weight = 1
        if (helper.isSqlServer()) {
            weight = 2
        } else if (helper.isOracle()) {
            weight = 3
        }
        if (helper.dbType().isSupportSequence()) {
            createSequence(sequenceName: 'scux_rcwl_pr_line_his_s', startValue: "1")
        }
        createTable(tableName: "scux_rcwl_pr_line_his", remarks: "采购申请行") {
            column(name: "pr_line_his_id", type: "bigint(20)", remarks: "") { constraints(primaryKey: true) }
            column(name: "pr_line_id", type: "bigint(20)", remarks: "") { constraints(nullable: "false") }
            column(name: "pr_header_id", type: "bigint(20)", remarks: "采购申请头ID") { constraints(nullable: "false") }
            column(name: "tenant_id", type: "bigint(20)", remarks: "租户ID") { constraints(nullable: "false") }
            column(name: "line_num", type: "int(11)", remarks: "行号")
            column(name: "display_line_num", type: "varchar(" + 150 * weight + ")", remarks: "展示行号") { constraints(nullable: "false") }
            column(name: "company_id", type: "bigint(20)", remarks: "公司ID") { constraints(nullable: "false") }
            column(name: "ou_id", type: "bigint(20)", remarks: "业务实体ID")
            column(name: "purchase_org_id", type: "bigint(20)", remarks: "采购组织ID")
            column(name: "purchase_agent_id", type: "bigint(20)", remarks: "采购员ID")
            column(name: "request_date", type: "date", remarks: "申请日期")
            column(name: "requested_by", type: "bigint(20)", defaultValue: "0", remarks: "申请人ID")
            column(name: "pr_requested_name", type: "varchar(" + 120 * weight + ")", remarks: "申请人")
            column(name: "inv_organization_id", type: "bigint(20)", remarks: "")
            column(name: "inventory_id", type: "bigint(20)", remarks: "库房ID")
            column(name: "item_id", type: "bigint(20)", remarks: "物料ID")
            column(name: "item_code", type: "varchar(" + 150 * weight + ")", remarks: "物料编码")
            column(name: "item_name", type: "varchar(" + 300 * weight + ")", remarks: "")
            column(name: "item_abc_class", type: "varchar(" + 60 * weight + ")", remarks: "物料ABC属性")
            column(name: "drawing_num", type: "varchar(" + 60 * weight + ")", remarks: "图号")
            column(name: "project_num", type: "varchar(" + 60 * weight + ")", remarks: "项目号")
            column(name: "project_name", type: "varchar(" + 60 * weight + ")", remarks: "项目名称")
            column(name: "crane_num", type: "varchar(" + 60 * weight + ")", remarks: "项目号车号")
            column(name: "product_id", type: "bigint(20)", remarks: "商品ID")
            column(name: "product_num", type: "varchar(" + 30 * weight + ")", remarks: "商品编码")
            column(name: "product_name", type: "varchar(" + 300 * weight + ")", remarks: "商品名称")
            column(name: "catalog_id", type: "bigint(20)", remarks: "商品目录ID")
            column(name: "catalog_name", type: "varchar(" + 360 * weight + ")", remarks: "商品目录名")
            column(name: "category_id", type: "bigint(20)", remarks: "自主品类ID")
            column(name: "uom_id", type: "bigint(20)", remarks: "单位ID")
            column(name: "quantity", type: "decimal(20,6)", remarks: "数量")
            column(name: "tax_id", type: "bigint(20)", remarks: "税率ID")
            column(name: "tax_rate", type: "decimal(10,2)", remarks: "税率")
            column(name: "currency_code", type: "varchar(" + 30 * weight + ")", remarks: "币种")
            column(name: "unit_price", type: "decimal(20,10)", remarks: "不含税单价")
            column(name: "tax_included_unit_price", type: "decimal(20,10)", remarks: "含税单价")
            column(name: "line_amount", type: "decimal(20,6)", remarks: "")
            column(name: "tax_included_line_amount", type: "decimal(20,6)", remarks: "")
            column(name: "needed_date", type: "date", remarks: "需求日期")
            column(name: "supplier_tenant_id", type: "bigint(20)", remarks: "供应商租户ID")
            column(name: "supplier_id", type: "bigint(20)", remarks: "供应商ID")
            column(name: "supplier_code", type: "varchar(" + 150 * weight + ")", remarks: "供应商编码")
            column(name: "supplier_name", type: "varchar(" + 360 * weight + ")", remarks: "供应商名称")
            column(name: "supplier_company_id", type: "bigint(20)", remarks: "供应商公司ID")
            column(name: "supplier_company_name", type: "varchar(" + 360 * weight + ")", remarks: "供应商公司描述")
            column(name: "execution_status_code", type: "varchar(" + 30 * weight + ")", remarks: "执行状态代码")
            column(name: "executed_date", type: "datetime", remarks: "执行时间")
            column(name: "executed_by", type: "bigint(20)", remarks: "执行人ID")
            column(name: "execution_bill_id", type: "bigint(20)", remarks: "目标单据ID")
            column(name: "execution_bill_num", type: "varchar(" + 150 * weight + ")", remarks: "目标单据编码")
            column(name: "execution_bill_data", type: "longtext", remarks: "目标单据附加数据")
            column(name: "assigned_flag", type: "tinyint(1)", defaultValue: "0", remarks: "分配标识") { constraints(nullable: "false") }
            column(name: "assigned_date", type: "datetime", remarks: "分配时间")
            column(name: "assigned_by", type: "bigint(20)", remarks: "分配人ID")
            column(name: "assigned_remark", type: "varchar(" + 480 * weight + ")", remarks: "分配原因")
            column(name: "cancelled_flag", type: "tinyint(1)", defaultValue: "0", remarks: "取消标识") { constraints(nullable: "false") }
            column(name: "cancelled_date", type: "datetime", remarks: "取消时间")
            column(name: "cancelled_by", type: "bigint(20)", remarks: "取消人ID")
            column(name: "cancelled_remark", type: "varchar(" + 480 * weight + ")", remarks: "取消原因")
            column(name: "closed_flag", type: "tinyint(1)", defaultValue: "0", remarks: "关闭标识") { constraints(nullable: "false") }
            column(name: "closed_date", type: "datetime", remarks: "关闭时间")
            column(name: "closed_by", type: "bigint(20)", remarks: "关闭人ID")
            column(name: "closed_remark", type: "varchar(" + 480 * weight + ")", remarks: "关闭原因")
            column(name: "suspend_flag", type: "tinyint(1)", defaultValue: "0", remarks: "暂挂标志")
            column(name: "suspend_date", type: "datetime", remarks: "暂挂日期")
            column(name: "suspend_remark", type: "varchar(" + 480 * weight + ")", remarks: "暂挂说明")
            column(name: "incorrect_flag", type: "tinyint(1)", defaultValue: "0", remarks: "异常标志")
            column(name: "incorrect_date", type: "datetime", remarks: "异常发生时间")
            column(name: "incorrect_msg", type: "longtext", remarks: "异常信息")
            column(name: "can_vat_flag", type: "tinyint(1)", remarks: "可开专票标识")
            column(name: "erp_edit_status", type: "varchar(" + 60 * weight + ")", defaultValue: "N", remarks: "ERP编辑状态")
            column(name: "attachment_uuid", type: "varchar(" + 50 * weight + ")", remarks: "附件UUID,功能: sprm-pr")
            column(name: "remark", type: "varchar(" + 480 * weight + ")", remarks: "行备注")
            column(name: "object_version_number", type: "bigint(20)", defaultValue: "1", remarks: "行版本号，用来处理锁") { constraints(nullable: "false") }
            column(name: "creation_date", type: "datetime", defaultValueComputed: "CURRENT_TIMESTAMP", remarks: "") { constraints(nullable: "false") }
            column(name: "created_by", type: "bigint(20)", defaultValue: "-1", remarks: "") { constraints(nullable: "false") }
            column(name: "last_updated_by", type: "bigint(20)", defaultValue: "-1", remarks: "") { constraints(nullable: "false") }
            column(name: "last_update_date", type: "datetime", defaultValueComputed: "CURRENT_TIMESTAMP", remarks: "") { constraints(nullable: "false") }
            column(name: "line_freight", type: "decimal(20,10)", defaultValue: "0.0000000000", remarks: "行运费")
            column(name: "execution_header_bill_id", type: "bigint(20)", remarks: "目标头单据ID")
            column(name: "execution_header_bill_num", type: "varchar(" + 150 * weight + ")", remarks: "目标头单据编码")
            column(name: "urgent_flag", type: "tinyint(1)", defaultValue: "0", remarks: "加急标识")
            column(name: "urgent_date", type: "datetime", remarks: "加急日期")
            column(name: "cost_id", type: "bigint(20)", remarks: "成本中心主键")
            column(name: "cost_code", type: "varchar(" + 30 * weight + ")", remarks: "成本中心编码")
            column(name: "account_subject_id", type: "bigint(20)", remarks: "总账主键")
            column(name: "account_subject_num", type: "varchar(" + 120 * weight + ")", remarks: "外部总账编码")
            column(name: "WBS", type: "varchar(" + 120 * weight + ")", remarks: "工作分解结构")
            column(name: "occupied_quantity", type: "decimal(20,6)", defaultValue: "0.000000", remarks: "剩余可创建订单数量")
            column(name: "last_purchase_price", type: "decimal(20,10)", remarks: "最近一次采购价")
            column(name: "pc_header_id", type: "bigint(20)", remarks: "采购协议头ID")
            column(name: "item_model", type: "varchar(" + 240 * weight + ")", remarks: "")
            column(name: "item_specs", type: "varchar(" + 480 * weight + ")", remarks: "")
            column(name: "item_properties", type: "varchar(" + 120 * weight + ")", remarks: "属性")
            column(name: "agent_id", type: "bigint(20)", remarks: "采购员ID")
            column(name: "keeper_user_id", type: "bigint(20)", remarks: "保管人用户ID")
            column(name: "accepter_user_id", type: "bigint(20)", remarks: "验收人用户ID")
            column(name: "cost_payer_user_id", type: "bigint(20)", remarks: "费用承担人用户ID")
            column(name: "address", type: "varchar(" + 60 * weight + ")", remarks: "地点，值集SPRM.PR_LINE.ADDRESS")
            column(name: "inner_po_num", type: "varchar(" + 60 * weight + ")", remarks: "内部订单号")
            column(name: "surface_treat_flag", type: "tinyint(1)", defaultValue: "0", remarks: "表面处理")
            column(name: "batch_no", type: "varchar(" + 60 * weight + ")", remarks: "批次号")
            column(name: "drawing_version", type: "varchar(" + 60 * weight + ")", remarks: "图纸版本")
            column(name: "supplier_item_code", type: "varchar(" + 60 * weight + ")", remarks: "供应商料号")
            column(name: "po_line_id", type: "bigint(20)", remarks: "订单行ID")
            column(name: "jd_price", type: "decimal(20,10)", remarks: "划线价")
            column(name: "req_type_code", type: "varchar(" + 20 * weight + ")", remarks: "申请类型")
            column(name: "purchase_org_group_name", type: "varchar(" + 360 * weight + ")", remarks: "采购组")
            column(name: "company_org_id", type: "bigint(20)", remarks: "公司组织id")
            column(name: "cost_anch_dep_id", type: "bigint(20)", remarks: "费用挂靠部门id")
            column(name: "exp_bear_dep_id", type: "bigint(20)", remarks: "费用承担部门id")
            column(name: "company_org_name", type: "varchar(" + 360 * weight + ")", remarks: "公司组织")
            column(name: "cost_anch_dep_desc", type: "varchar(" + 200 * weight + ")", remarks: "费用挂靠部门")
            column(name: "exp_bear_dep", type: "varchar(" + 200 * weight + ")", remarks: "费用承担部门")
            column(name: "source_platform_code", type: "varchar(" + 200 * weight + ")", remarks: "来源平台")
            column(name: "accepter_user_name", type: "varchar(" + 200 * weight + ")", remarks: "验收人")
            column(name: "agent_name", type: "varchar(" + 200 * weight + ")", remarks: "采购员")
            column(name: "keeper_user_name", type: "varchar(" + 200 * weight + ")", remarks: "保管人")
            column(name: "tax_code", type: "bigint(20)", remarks: "税种")
            column(name: "overseas_procurement", type: "tinyint(1)", defaultValue: "0", remarks: "境外采购") { constraints(nullable: "false") }
            column(name: "frame_agreement_num", type: "varchar(" + 30 * weight + ")", remarks: "框架协议编码")
            column(name: "wbs_code", type: "varchar(" + 30 * weight + ")", remarks: "wbs编码")
            column(name: "supplier_item_name", type: "varchar(" + 120 * weight + ")", remarks: "供应商料号描述")
            column(name: "tax_without_freight_price", type: "decimal(20,10)", remarks: "含税单价(不含运费)")
            column(name: "benchmark_price", type: "decimal(20,10)", remarks: "基准价")
            column(name: "change_percent", type: "decimal(20,10)", remarks: "涨跌幅")
            column(name: "purchase_line_type_id", type: "bigint(20)", remarks: "采购行类型ID")
            column(name: "unit_price_batch", type: "decimal(10,0)", remarks: "价格批量(每)")
            column(name: "project_category", type: "varchar(" + 30 * weight + ")", remarks: "项目类别")
            column(name: "assets", type: "varchar(" + 120 * weight + ")", remarks: "资产")
            column(name: "asset_child_num", type: "varchar(" + 120 * weight + ")", remarks: "资产子编号")
            column(name: "account_assign_type_id", type: "bigint(20)", remarks: "账户分配类别ID")
            column(name: "freight_line_flag", type: "tinyint(1)", defaultValue: "0", remarks: "新电商运费行标识")
            column(name: "budget_io_flag", type: "tinyint(1)", defaultValue: "0", remarks: "预算内外标识") { constraints(nullable: "false") }
            column(name: "tax_included_budget_unit_price", type: "decimal(20,10)", remarks: "预算单价(含税)")
            column(name: "quality_standard", type: "varchar(" + 120 * weight + ")", remarks: "质量标准")
            column(name: "attribute_varchar1", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段1")
            column(name: "attribute_varchar2", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段2")
            column(name: "attribute_varchar3", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段3")
            column(name: "attribute_varchar4", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段4")
            column(name: "attribute_varchar5", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段5")
            column(name: "attribute_varchar6", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段6")
            column(name: "attribute_varchar7", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段7")
            column(name: "attribute_varchar8", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段8")
            column(name: "attribute_varchar9", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段9")
            column(name: "attribute_varchar10", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段10")
            column(name: "attribute_varchar11", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段11")
            column(name: "attribute_varchar12", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段12")
            column(name: "attribute_varchar13", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段13")
            column(name: "attribute_varchar14", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段14")
            column(name: "attribute_varchar15", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段15")
            column(name: "attribute_varchar16", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段16")
            column(name: "attribute_varchar17", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段17")
            column(name: "attribute_varchar18", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段18")
            column(name: "attribute_varchar19", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段19")
            column(name: "attribute_varchar20", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段20")
            column(name: "attribute_varchar21", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段21")
            column(name: "attribute_varchar22", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段22")
            column(name: "attribute_varchar23", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段23")
            column(name: "attribute_varchar24", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段24")
            column(name: "attribute_varchar25", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段25")
            column(name: "attribute_varchar26", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段26")
            column(name: "attribute_varchar27", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段27")
            column(name: "attribute_varchar28", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段28")
            column(name: "attribute_varchar29", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段29")
            column(name: "attribute_varchar30", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段30")
            column(name: "attribute_varchar31", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段31")
            column(name: "attribute_varchar32", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段32")
            column(name: "attribute_varchar33", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段33")
            column(name: "attribute_varchar34", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段34")
            column(name: "attribute_varchar35", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段35")
            column(name: "attribute_varchar36", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段36")
            column(name: "attribute_varchar37", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段37")
            column(name: "attribute_varchar38", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段38")
            column(name: "attribute_varchar39", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段39")
            column(name: "attribute_varchar40", type: "varchar(" + 100 * weight + ")", remarks: "字符扩展字段40")
            column(name: "attribute_longtext1", type: "longtext", remarks: "长字符扩展字段1")
            column(name: "attribute_longtext2", type: "longtext", remarks: "长字符扩展字段2")
            column(name: "attribute_longtext3", type: "longtext", remarks: "长字符扩展字段3")
            column(name: "attribute_longtext4", type: "longtext", remarks: "长字符扩展字段4")
            column(name: "attribute_longtext5", type: "longtext", remarks: "长字符扩展字段5")
            column(name: "attribute_longtext6", type: "longtext", remarks: "长字符扩展字段6")
            column(name: "attribute_longtext7", type: "longtext", remarks: "长字符扩展字段7")
            column(name: "attribute_longtext8", type: "longtext", remarks: "长字符扩展字段8")
            column(name: "attribute_longtext9", type: "longtext", remarks: "长字符扩展字段9")
            column(name: "attribute_longtext10", type: "longtext", remarks: "长字符扩展字段10")
            column(name: "attribute_bigint1", type: "bigint(20)", remarks: "整数扩展字段1")
            column(name: "attribute_bigint2", type: "bigint(20)", remarks: "整数扩展字段2")
            column(name: "attribute_bigint3", type: "bigint(20)", remarks: "整数扩展字段3")
            column(name: "attribute_bigint4", type: "bigint(20)", remarks: "整数扩展字段4")
            column(name: "attribute_bigint5", type: "bigint(20)", remarks: "整数扩展字段5")
            column(name: "attribute_bigint6", type: "bigint(20)", remarks: "整数扩展字段6")
            column(name: "attribute_bigint7", type: "bigint(20)", remarks: "整数扩展字段7")
            column(name: "attribute_bigint8", type: "bigint(20)", remarks: "整数扩展字段8")
            column(name: "attribute_bigint9", type: "bigint(20)", remarks: "整数扩展字段9")
            column(name: "attribute_bigint10", type: "bigint(20)", remarks: "整数扩展字段10")
            column(name: "attribute_bigint11", type: "bigint(20)", remarks: "整数扩展字段11")
            column(name: "attribute_bigint12", type: "bigint(20)", remarks: "整数扩展字段12")
            column(name: "attribute_bigint13", type: "bigint(20)", remarks: "整数扩展字段13")
            column(name: "attribute_bigint14", type: "bigint(20)", remarks: "整数扩展字段14")
            column(name: "attribute_bigint15", type: "bigint(20)", remarks: "整数扩展字段15")
            column(name: "attribute_bigint16", type: "bigint(20)", remarks: "整数扩展字段16")
            column(name: "attribute_bigint17", type: "bigint(20)", remarks: "整数扩展字段17")
            column(name: "attribute_bigint18", type: "bigint(20)", remarks: "整数扩展字段18")
            column(name: "attribute_bigint19", type: "bigint(20)", remarks: "整数扩展字段19")
            column(name: "attribute_bigint20", type: "bigint(20)", remarks: "整数扩展字段20")
            column(name: "attribute_bigint21", type: "bigint(20)", remarks: "整数扩展字段21")
            column(name: "attribute_bigint22", type: "bigint(20)", remarks: "整数扩展字段22")
            column(name: "attribute_bigint23", type: "bigint(20)", remarks: "整数扩展字段23")
            column(name: "attribute_bigint24", type: "bigint(20)", remarks: "整数扩展字段24")
            column(name: "attribute_bigint25", type: "bigint(20)", remarks: "整数扩展字段25")
            column(name: "attribute_bigint26", type: "bigint(20)", remarks: "整数扩展字段26")
            column(name: "attribute_bigint27", type: "bigint(20)", remarks: "整数扩展字段27")
            column(name: "attribute_bigint28", type: "bigint(20)", remarks: "整数扩展字段28")
            column(name: "attribute_bigint29", type: "bigint(20)", remarks: "整数扩展字段29")
            column(name: "attribute_bigint30", type: "bigint(20)", remarks: "整数扩展字段30")
            column(name: "attribute_tinyint1", type: "tinyint(4)", remarks: "小整数扩展字段1")
            column(name: "attribute_tinyint2", type: "tinyint(4)", remarks: "小整数扩展字段2")
            column(name: "attribute_tinyint3", type: "tinyint(4)", remarks: "小整数扩展字段3")
            column(name: "attribute_tinyint4", type: "tinyint(4)", remarks: "小整数扩展字段4")
            column(name: "attribute_tinyint5", type: "tinyint(4)", remarks: "小整数扩展字段5")
            column(name: "attribute_tinyint6", type: "tinyint(4)", remarks: "小整数扩展字段6")
            column(name: "attribute_tinyint7", type: "tinyint(4)", remarks: "小整数扩展字段7")
            column(name: "attribute_tinyint8", type: "tinyint(4)", remarks: "小整数扩展字段8")
            column(name: "attribute_tinyint9", type: "tinyint(4)", remarks: "小整数扩展字段9")
            column(name: "attribute_tinyint10", type: "tinyint(4)", remarks: "小整数扩展字段10")
            column(name: "attribute_tinyint11", type: "tinyint(4)", remarks: "小整数扩展字段11")
            column(name: "attribute_tinyint12", type: "tinyint(4)", remarks: "小整数扩展字段12")
            column(name: "attribute_tinyint13", type: "tinyint(4)", remarks: "小整数扩展字段13")
            column(name: "attribute_tinyint14", type: "tinyint(4)", remarks: "小整数扩展字段14")
            column(name: "attribute_tinyint15", type: "tinyint(4)", remarks: "小整数扩展字段15")
            column(name: "attribute_tinyint16", type: "tinyint(4)", remarks: "小整数扩展字段16")
            column(name: "attribute_tinyint17", type: "tinyint(4)", remarks: "小整数扩展字段17")
            column(name: "attribute_tinyint18", type: "tinyint(4)", remarks: "小整数扩展字段18")
            column(name: "attribute_tinyint19", type: "tinyint(4)", remarks: "小整数扩展字段19")
            column(name: "attribute_tinyint20", type: "tinyint(4)", remarks: "小整数扩展字段20")
            column(name: "attribute_decimal1", type: "decimal(22,10)", remarks: "小数扩展字段1")
            column(name: "attribute_decimal2", type: "decimal(22,10)", remarks: "小数扩展字段2")
            column(name: "attribute_decimal3", type: "decimal(22,10)", remarks: "小数扩展字段3")
            column(name: "attribute_decimal4", type: "decimal(22,10)", remarks: "小数扩展字段4")
            column(name: "attribute_decimal5", type: "decimal(22,10)", remarks: "小数扩展字段5")
            column(name: "attribute_decimal6", type: "decimal(22,10)", remarks: "小数扩展字段6")
            column(name: "attribute_decimal7", type: "decimal(22,10)", remarks: "小数扩展字段7")
            column(name: "attribute_decimal8", type: "decimal(22,10)", remarks: "小数扩展字段8")
            column(name: "attribute_decimal9", type: "decimal(22,10)", remarks: "小数扩展字段9")
            column(name: "attribute_decimal10", type: "decimal(22,10)", remarks: "小数扩展字段10")
            column(name: "attribute_decimal11", type: "decimal(22,10)", remarks: "小数扩展字段11")
            column(name: "attribute_decimal12", type: "decimal(22,10)", remarks: "小数扩展字段12")
            column(name: "attribute_decimal13", type: "decimal(22,10)", remarks: "小数扩展字段13")
            column(name: "attribute_decimal14", type: "decimal(22,10)", remarks: "小数扩展字段14")
            column(name: "attribute_decimal15", type: "decimal(22,10)", remarks: "小数扩展字段15")
            column(name: "attribute_decimal16", type: "decimal(22,10)", remarks: "小数扩展字段16")
            column(name: "attribute_decimal17", type: "decimal(22,10)", remarks: "小数扩展字段17")
            column(name: "attribute_decimal18", type: "decimal(22,10)", remarks: "小数扩展字段18")
            column(name: "attribute_decimal19", type: "decimal(22,10)", remarks: "小数扩展字段19")
            column(name: "attribute_decimal20", type: "decimal(22,10)", remarks: "小数扩展字段20")
            column(name: "attribute_decimal21", type: "decimal(22,10)", remarks: "小数扩展字段21")
            column(name: "attribute_decimal22", type: "decimal(22,10)", remarks: "小数扩展字段22")
            column(name: "attribute_decimal23", type: "decimal(22,10)", remarks: "小数扩展字段23")
            column(name: "attribute_decimal24", type: "decimal(22,10)", remarks: "小数扩展字段24")
            column(name: "attribute_decimal25", type: "decimal(22,10)", remarks: "小数扩展字段25")
            column(name: "attribute_decimal26", type: "decimal(22,10)", remarks: "小数扩展字段26")
            column(name: "attribute_decimal27", type: "decimal(22,10)", remarks: "小数扩展字段27")
            column(name: "attribute_decimal28", type: "decimal(22,10)", remarks: "小数扩展字段28")
            column(name: "attribute_decimal29", type: "decimal(22,10)", remarks: "小数扩展字段29")
            column(name: "attribute_decimal30", type: "decimal(22,10)", remarks: "小数扩展字段30")
            column(name: "attribute_datetime1", type: "datetime", remarks: "日期时间扩展字段1")
            column(name: "attribute_datetime2", type: "datetime", remarks: "日期时间扩展字段2")
            column(name: "attribute_datetime3", type: "datetime", remarks: "日期时间扩展字段3")
            column(name: "attribute_datetime4", type: "datetime", remarks: "日期时间扩展字段4")
            column(name: "attribute_datetime5", type: "datetime", remarks: "日期时间扩展字段5")
            column(name: "attribute_datetime6", type: "datetime", remarks: "日期时间扩展字段6")
            column(name: "attribute_datetime7", type: "datetime", remarks: "日期时间扩展字段7")
            column(name: "attribute_datetime8", type: "datetime", remarks: "日期时间扩展字段8")
            column(name: "attribute_datetime9", type: "datetime", remarks: "日期时间扩展字段9")
            column(name: "attribute_datetime10", type: "datetime", remarks: "日期时间扩展字段10")
            column(name: "attribute_datetime11", type: "datetime", remarks: "日期时间扩展字段11")
            column(name: "attribute_datetime12", type: "datetime", remarks: "日期时间扩展字段12")
            column(name: "attribute_datetime13", type: "datetime", remarks: "日期时间扩展字段13")
            column(name: "attribute_datetime14", type: "datetime", remarks: "日期时间扩展字段14")
            column(name: "attribute_datetime15", type: "datetime", remarks: "日期时间扩展字段15")
            column(name: "attribute_datetime16", type: "datetime", remarks: "日期时间扩展字段16")
            column(name: "attribute_datetime17", type: "datetime", remarks: "日期时间扩展字段17")
            column(name: "attribute_datetime18", type: "datetime", remarks: "日期时间扩展字段18")
            column(name: "attribute_datetime19", type: "datetime", remarks: "日期时间扩展字段19")
            column(name: "attribute_datetime20", type: "datetime", remarks: "日期时间扩展字段20")
            column(name: "attribute_date1", type: "date", remarks: "日期扩展字段1")
            column(name: "attribute_date2", type: "date", remarks: "日期扩展字段2")
            column(name: "attribute_date3", type: "date", remarks: "日期扩展字段3")
            column(name: "attribute_date4", type: "date", remarks: "日期扩展字段4")
            column(name: "attribute_date5", type: "date", remarks: "日期扩展字段5")
            column(name: "attribute_date6", type: "date", remarks: "日期扩展字段6")
            column(name: "attribute_date7", type: "date", remarks: "日期扩展字段7")
            column(name: "attribute_date8", type: "date", remarks: "日期扩展字段8")
            column(name: "attribute_date9", type: "date", remarks: "日期扩展字段9")
            column(name: "attribute_date10", type: "date", remarks: "日期扩展字段10")
            column(name: "attribute_date11", type: "date", remarks: "日期扩展字段11")
            column(name: "attribute_date12", type: "date", remarks: "日期扩展字段12")
            column(name: "attribute_date13", type: "date", remarks: "日期扩展字段13")
            column(name: "attribute_date14", type: "date", remarks: "日期扩展字段14")
            column(name: "attribute_date15", type: "date", remarks: "日期扩展字段15")
            column(name: "attribute_date16", type: "date", remarks: "日期扩展字段16")
            column(name: "attribute_date17", type: "date", remarks: "日期扩展字段17")
            column(name: "attribute_date18", type: "date", remarks: "日期扩展字段18")
            column(name: "attribute_date19", type: "date", remarks: "日期扩展字段19")
            column(name: "attribute_date20", type: "date", remarks: "日期扩展字段20")
            column(name: "execution_strategy_code", type: "varchar(" + 20 * weight + ")", remarks: "执行策略")
            column(name: "business_card_flag", type: "tinyint(1)", remarks: "")
            column(name: "budget_account_id", type: "bigint(20)", remarks: "预算科目ID")
            column(name: "receiver_information", type: "varchar(" + 480 * weight + ")", remarks: "收货信息")
            column(name: "receive_address", type: "varchar(" + 1000 * weight + ")", remarks: "收货地址")
            column(name: "receive_contact_name", type: "varchar(" + 255 * weight + ")", remarks: "收货联系人")
            column(name: "receive_tel_num", type: "varchar(" + 30 * weight + ")", remarks: "收货联系电话")
            column(name: "cart_user_id", type: "bigint(20)", remarks: "卡片用户ID")
            column(name: "cart_user_type", type: "varchar(" + 40 * weight + ")", remarks: "卡片类型 GROUP/EMPLOYEE")
            column(name: "change_order_code", type: "varchar(" + 30 * weight + ")", remarks: "自动生成订单成功失败标识")
            column(name: "change_order_message", type: "longtext", remarks: "自动生成订单报错信息")
            column(name: "budget_account_deptno", type: "varchar(" + 30 * weight + ")", remarks: "预算部门编号")
            column(name: "budget_account_price", type: "decimal(10,0)", remarks: "预算金额")
            column(name: "document_id", type: "varchar(" + 240 * weight + ")", remarks: "预算单据ID")
            column(name: "exchange_rate", type: "decimal(20,10)", defaultValue: "1.0000000000", remarks: "汇率")
            column(name: "local_currency_tax_unit", type: "decimal(20,10)", defaultValue: "0.0000000000", remarks: "本币含税单价")
            column(name: "local_currency_no_tax_unit", type: "decimal(20,10)", defaultValue: "0.0000000000", remarks: "本币不含税单价")
            column(name: "local_currency_tax_sum", type: "decimal(20,10)", defaultValue: "0.0000000000", remarks: "本币含税金额")
            column(name: "local_currency_no_tax_sum", type: "decimal(20,10)", defaultValue: "0.0000000000", remarks: "本币不含税金额")
            column(name: "exchange_rate_date", type: "date", remarks: "汇率日期")
            column(name: "budget_account_num", type: "varchar(" + 60 * weight + ")", remarks: "预算科目编码")
            column(name: "is_push_assets_flag", type: "tinyint(4)", remarks: "品类是否推资产标识")
            column(name: "version", type: "bigint(20)", defaultValue: "0", remarks: "版本") { constraints(nullable: "false") }

        }
        createIndex(tableName: "scux_rcwl_pr_line_his", indexName: "sprm_pr_line_u2") {
            column(name: "execution_header_bill_id")
        }

        addUniqueConstraint(columnNames: "pr_header_id,line_num,version", tableName: "scux_rcwl_pr_line_his", constraintName: "sprm_pr_line_u1")
    }
}